[package]
name = "rust-xworm"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_SystemInformation",
    "Win32_Security",
    "Win32_System_Registry",
    "Win32_Storage_FileSystem",
    "Win32_UI_Input_KeyboardAndMouse",
] }
sysinfo = "0.31"
reqwest = { version = "0.12", features = ["blocking", "native-tls"] }
rc4 = "0.1"
base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
