[package]
name = "kernel_apc"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.54", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_Devices_DeviceAndDriverInstallation",
] }
